name: Create Azure VM

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch

jobs:
  create-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1

      - name: Log in to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Create resource group
        run: az group create --name myResourceGroup --location eastus

      - name: Create VM
        run: az vm create --resource-group myResourceGroup --name myVM --image UbuntuLTS --admin-username azureuser --admin-password Azure12345678 --size Standard_DS1_v2 --generate-ssh-keys
